/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.UserDAO;
import models.User;
import utils.Session;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author admin
 */
public class AdminFrame extends javax.swing.JFrame {
    
    private JTable table;
    private DefaultTableModel tableModel;
    private UserDAO userDAO;
    
    /**
     * Creates new form AdminFrame
     */
    public AdminFrame() {
        initComponents();
        userDAO = new UserDAO();
        initUI();
        loadData();
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void initUI() {
        setTitle("Admin - Quản lý Users");
        setSize(900, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        // Header
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(239, 68, 68));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        
        JLabel lblTitle = new JLabel("QUẢN LÝ NGƯỜI DÙNG");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 18));
        lblTitle.setForeground(Color.WHITE);
        headerPanel.add(lblTitle, BorderLayout.WEST);
        
        JButton btnLogout = new JButton("Đăng xuất");
        btnLogout.addActionListener(e -> logout());
        headerPanel.add(btnLogout, BorderLayout.EAST);
        
        add(headerPanel, BorderLayout.NORTH);
        
        // Table
        String[] columns = {"ID", "Username", "Fullname", "Email", "Role"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Read-only
            }
        };
        table = new JTable(tableModel);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);
        
        // Button panel
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        JButton btnAdd = new JButton("➕ Thêm");
        btnAdd.addActionListener(e -> addUser());
        btnPanel.add(btnAdd);
        
        JButton btnEdit = new JButton("✏️ Sửa");
        btnEdit.addActionListener(e -> editUser());
        btnPanel.add(btnEdit);
        
        JButton btnDelete = new JButton("🗑️ Xóa");
        btnDelete.addActionListener(e -> deleteUser());
        btnPanel.add(btnDelete);
        
        JButton btnRefresh = new JButton("🔄 Làm mới");
        btnRefresh.addActionListener(e -> loadData());
        btnPanel.add(btnRefresh);
        
        add(btnPanel, BorderLayout.SOUTH);
    }
    
    private void loadData() {
        tableModel.setRowCount(0);
        List<User> users = userDAO.findAll();
        for (User user : users) {
            tableModel.addRow(new Object[]{
                user.getId(),
                user.getUsername(),
                user.getFullname(),
                user.getEmail(),
                user.getRole()
            });
        }
    }
    
    private void addUser() {
        JDialog dialog = new JDialog(this, "Thêm User", true);
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        
        JPanel panel = new JPanel(new GridLayout(6, 2, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JTextField txtUsername = new JTextField();
        JTextField txtPassword = new JTextField();
        JTextField txtFullname = new JTextField();
        JTextField txtEmail = new JTextField();
        JComboBox<String> cboRole = new JComboBox<>(new String[]{"ADMIN", "INSTRUCTOR", "STUDENT"});
        
        panel.add(new JLabel("Username:"));
        panel.add(txtUsername);
        panel.add(new JLabel("Password:"));
        panel.add(txtPassword);
        panel.add(new JLabel("Fullname:"));
        panel.add(txtFullname);
        panel.add(new JLabel("Email:"));
        panel.add(txtEmail);
        panel.add(new JLabel("Role:"));
        panel.add(cboRole);
        
        JButton btnSave = new JButton("Lưu");
        JButton btnCancel = new JButton("Hủy");
        
        btnSave.addActionListener(e -> {
            User user = new User(
                txtUsername.getText(),
                txtPassword.getText(),
                txtFullname.getText(),
                txtEmail.getText(),
                cboRole.getSelectedItem().toString()
            );
            
            if (userDAO.insert(user)) {
                JOptionPane.showMessageDialog(dialog, "Thêm thành công!");
                loadData();
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Thêm thất bại!");
            }
        });
        
        btnCancel.addActionListener(e -> dialog.dispose());
        
        panel.add(btnSave);
        panel.add(btnCancel);
        
        dialog.add(panel);
        dialog.setVisible(true);
    }
    
    private void editUser() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn user!");
            return;
        }
        
        int id = (int) tableModel.getValueAt(row, 0);
        User user = userDAO.findById(id);
        
        JDialog dialog = new JDialog(this, "Sửa User", true);
        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        
        JPanel panel = new JPanel(new GridLayout(6, 2, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JTextField txtUsername = new JTextField(user.getUsername());
        JTextField txtPassword = new JTextField(user.getPassword());
        JTextField txtFullname = new JTextField(user.getFullname());
        JTextField txtEmail = new JTextField(user.getEmail());
        JComboBox<String> cboRole = new JComboBox<>(new String[]{"ADMIN", "INSTRUCTOR", "STUDENT"});
        cboRole.setSelectedItem(user.getRole());
        
        panel.add(new JLabel("Username:"));
        panel.add(txtUsername);
        panel.add(new JLabel("Password:"));
        panel.add(txtPassword);
        panel.add(new JLabel("Fullname:"));
        panel.add(txtFullname);
        panel.add(new JLabel("Email:"));
        panel.add(txtEmail);
        panel.add(new JLabel("Role:"));
        panel.add(cboRole);
        
        JButton btnSave = new JButton("Lưu");
        JButton btnCancel = new JButton("Hủy");
        
        btnSave.addActionListener(e -> {
            user.setUsername(txtUsername.getText());
            user.setPassword(txtPassword.getText());
            user.setFullname(txtFullname.getText());
            user.setEmail(txtEmail.getText());
            user.setRole(cboRole.getSelectedItem().toString());
            
            if (userDAO.update(user)) {
                JOptionPane.showMessageDialog(dialog, "Cập nhật thành công!");
                loadData();
                dialog.dispose();
            } else {
                JOptionPane.showMessageDialog(dialog, "Cập nhật thất bại!");
            }
        });
        
        btnCancel.addActionListener(e -> dialog.dispose());
        
        panel.add(btnSave);
        panel.add(btnCancel);
        
        dialog.add(panel);
        dialog.setVisible(true);
    }
    
    private void deleteUser() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn user!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa?");
        if (confirm == JOptionPane.YES_OPTION) {
            int id = (int) tableModel.getValueAt(row, 0);
            if (userDAO.delete(id)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }
    
    private void logout() {
        Session.logout();
        new LoginFrame().setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
