/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.CourseDAO;
import models.Course;
import utils.Session;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author admin
 */
public class InstructorFrame extends javax.swing.JFrame {
    
    private JTable table;
    private DefaultTableModel tableModel;
    private CourseDAO courseDAO;
    
    /**
     * Creates new form InstructorFrame
     */
    public InstructorFrame() {
        courseDAO = new CourseDAO();
        initUI();
        loadData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initUI() {
        setTitle("Instructor - Quản lý Khóa học");
        setSize(900, 600);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        // Header
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(16, 185, 129));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        
        JLabel lblTitle = new JLabel("QUẢN LÝ KHÓA HỌC");
        lblTitle.setFont(new Font("Arial", Font.BOLD, 18));
        lblTitle.setForeground(Color.WHITE);
        headerPanel.add(lblTitle, BorderLayout.WEST);
        
        JButton btnLogout = new JButton("Đăng xuất");
        btnLogout.addActionListener(e -> logout());
        headerPanel.add(btnLogout, BorderLayout.EAST);
        
        add(headerPanel, BorderLayout.NORTH);
        
        // Table
        String[] columns = {"ID", "Tên khóa học", "Mô tả", "Giá", "Giảng viên"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table = new JTable(tableModel);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(table);
        add(scrollPane, BorderLayout.CENTER);
        
        // Buttons
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        JButton btnAdd = new JButton("➕ Thêm khóa học");
        btnAdd.addActionListener(e -> addCourse());
        btnPanel.add(btnAdd);
        
        JButton btnEdit = new JButton("✏️ Sửa");
        btnEdit.addActionListener(e -> editCourse());
        btnPanel.add(btnEdit);
        
        JButton btnDelete = new JButton("🗑️ Xóa");
        btnDelete.addActionListener(e -> deleteCourse());
        btnPanel.add(btnDelete);
        
        JButton btnRefresh = new JButton("🔄 Làm mới");
        btnRefresh.addActionListener(e -> loadData());
        btnPanel.add(btnRefresh);
        
        add(btnPanel, BorderLayout.SOUTH);
    }
    
    private void loadData() {
        tableModel.setRowCount(0);
        // Chỉ load courses của instructor hiện tại
        int instructorId = Session.getCurrentUser().getId();
        List<Course> courses = courseDAO.findByInstructor(instructorId);
        
        for (Course course : courses) {
            tableModel.addRow(new Object[]{
                course.getId(),
                course.getTitle(),
                course.getDescription(),
                course.getPriceText(),
                course.getInstructorName()
            });
        }
    }
    
    private void addCourse() {
        JDialog dialog = new JDialog(this, "Thêm khóa học", true);
        dialog.setSize(450, 300);
        dialog.setLocationRelativeTo(this);
        
        JPanel panel = new JPanel(new GridLayout(5, 2, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JTextField txtTitle = new JTextField();
        JTextArea txtDescription = new JTextArea(3, 20);
        txtDescription.setLineWrap(true);
        JTextField txtPrice = new JTextField();
        
        panel.add(new JLabel("Tên khóa học:"));
        panel.add(txtTitle);
        panel.add(new JLabel("Mô tả:"));
        panel.add(new JScrollPane(txtDescription));
        panel.add(new JLabel("Giá (VNĐ):"));
        panel.add(txtPrice);
        
        JButton btnSave = new JButton("Lưu");
        JButton btnCancel = new JButton("Hủy");
        
        btnSave.addActionListener(e -> {
            try {
                Course course = new Course(
                    txtTitle.getText(),
                    txtDescription.getText(),
                    Session.getCurrentUser().getId(),
                    Double.parseDouble(txtPrice.getText())
                );
                
                if (courseDAO.insert(course)) {
                    JOptionPane.showMessageDialog(dialog, "Thêm thành công!");
                    loadData();
                    dialog.dispose();
                } else {
                    JOptionPane.showMessageDialog(dialog, "Thêm thất bại!");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Giá không hợp lệ!");
            }
        });
        
        btnCancel.addActionListener(e -> dialog.dispose());
        
        panel.add(btnSave);
        panel.add(btnCancel);
        
        dialog.add(panel);
        dialog.setVisible(true);
    }
    
    private void editCourse() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khóa học!");
            return;
        }
        
        int id = (int) tableModel.getValueAt(row, 0);
        Course course = courseDAO.findById(id);
        
        JDialog dialog = new JDialog(this, "Sửa khóa học", true);
        dialog.setSize(450, 300);
        dialog.setLocationRelativeTo(this);
        
        JPanel panel = new JPanel(new GridLayout(5, 2, 5, 5));
        panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        
        JTextField txtTitle = new JTextField(course.getTitle());
        JTextArea txtDescription = new JTextArea(course.getDescription(), 3, 20);
        txtDescription.setLineWrap(true);
        JTextField txtPrice = new JTextField(String.valueOf(course.getPrice()));
        
        panel.add(new JLabel("Tên khóa học:"));
        panel.add(txtTitle);
        panel.add(new JLabel("Mô tả:"));
        panel.add(new JScrollPane(txtDescription));
        panel.add(new JLabel("Giá (VNĐ):"));
        panel.add(txtPrice);
        
        JButton btnSave = new JButton("Lưu");
        JButton btnCancel = new JButton("Hủy");
        
        btnSave.addActionListener(e -> {
            try {
                course.setTitle(txtTitle.getText());
                course.setDescription(txtDescription.getText());
                course.setPrice(Double.parseDouble(txtPrice.getText()));
                
                if (courseDAO.update(course)) {
                    JOptionPane.showMessageDialog(dialog, "Cập nhật thành công!");
                    loadData();
                    dialog.dispose();
                } else {
                    JOptionPane.showMessageDialog(dialog, "Cập nhật thất bại!");
                }
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(dialog, "Giá không hợp lệ!");
            }
        });
        
        btnCancel.addActionListener(e -> dialog.dispose());
        
        panel.add(btnSave);
        panel.add(btnCancel);
        
        dialog.add(panel);
        dialog.setVisible(true);
    }
    
    private void deleteCourse() {
        int row = table.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khóa học!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Xác nhận xóa khóa học này?");
        if (confirm == JOptionPane.YES_OPTION) {
            int id = (int) tableModel.getValueAt(row, 0);
            if (courseDAO.delete(id)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                loadData();
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại!");
            }
        }
    }
    
    private void logout() {
        Session.logout();
        new LoginFrame().setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstructorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstructorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstructorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstructorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
