/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import dao.CourseDAO;
import dao.EnrollmentDAO;
import models.Course;
import models.Enrollment;
import utils.Session;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

/**
 *
 * @author admin
 */
public class StudentFrame extends javax.swing.JFrame {
    
    private JTable tableCourses;
    private DefaultTableModel modelCourses;
    private JTable tableMyEnrollments;
    private DefaultTableModel modelEnrollments;
    private CourseDAO courseDAO;
    private EnrollmentDAO enrollmentDAO;
    
    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        courseDAO = new CourseDAO();
        enrollmentDAO = new EnrollmentDAO();
        initUI();
        loadData();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void initUI() {
        setTitle("Student - Khóa học");
        setSize(1000, 700);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        // Header
        JPanel headerPanel = new JPanel(new BorderLayout());
        headerPanel.setBackground(new Color(37, 99, 235));
        headerPanel.setBorder(BorderFactory.createEmptyBorder(10, 20, 10, 20));
        
        JLabel lblTitle = new JLabel("HỌC VIÊN: " + Session.getCurrentUser().getFullname());
        lblTitle.setFont(new Font("Arial", Font.BOLD, 18));
        lblTitle.setForeground(Color.WHITE);
        headerPanel.add(lblTitle, BorderLayout.WEST);
        
        JButton btnLogout = new JButton("Đăng xuất");
        btnLogout.addActionListener(e -> logout());
        headerPanel.add(btnLogout, BorderLayout.EAST);
        
        add(headerPanel, BorderLayout.NORTH);
        
        // Main content with tabs
        JTabbedPane tabbedPane = new JTabbedPane();
        
        // Tab 1: All Courses
        JPanel panelAllCourses = createAllCoursesPanel();
        tabbedPane.addTab("📚 Tất cả khóa học", panelAllCourses);
        
        // Tab 2: My Enrollments
        JPanel panelMyEnrollments = createMyEnrollmentsPanel();
        tabbedPane.addTab("📖 Khóa học của tôi", panelMyEnrollments);
        
        add(tabbedPane, BorderLayout.CENTER);
    }
    
    private JPanel createAllCoursesPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        
        // Table
        String[] columns = {"ID", "Tên khóa học", "Mô tả", "Giá", "Giảng viên"};
        modelCourses = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableCourses = new JTable(modelCourses);
        tableCourses.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableCourses.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(tableCourses);
        panel.add(scrollPane, BorderLayout.CENTER);
        
        // Buttons
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        JButton btnEnroll = new JButton("✅ Đăng ký học");
        btnEnroll.setBackground(new Color(16, 185, 129));
        btnEnroll.setForeground(Color.WHITE);
        btnEnroll.addActionListener(e -> enrollCourse());
        btnPanel.add(btnEnroll);
        
        JButton btnRefresh = new JButton("🔄 Làm mới");
        btnRefresh.addActionListener(e -> loadAllCourses());
        btnPanel.add(btnRefresh);
        
        panel.add(btnPanel, BorderLayout.SOUTH);
        
        return panel;
    }
    
    private JPanel createMyEnrollmentsPanel() {
        JPanel panel = new JPanel(new BorderLayout());
        
        // Table
        String[] columns = {"ID", "Khóa học", "Ngày đăng ký"};
        modelEnrollments = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableMyEnrollments = new JTable(modelEnrollments);
        tableMyEnrollments.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableMyEnrollments.setRowHeight(25);
        
        JScrollPane scrollPane = new JScrollPane(tableMyEnrollments);
        panel.add(scrollPane, BorderLayout.CENTER);
        
        // Buttons
        JPanel btnPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 10, 10));
        
        JButton btnRefresh = new JButton("🔄 Làm mới");
        btnRefresh.addActionListener(e -> loadMyEnrollments());
        btnPanel.add(btnRefresh);
        
        panel.add(btnPanel, BorderLayout.SOUTH);
        
        return panel;
    }
    
    private void loadData() {
        loadAllCourses();
        loadMyEnrollments();
    }
    
    private void loadAllCourses() {
        modelCourses.setRowCount(0);
        List<Course> courses = courseDAO.findAll();
        
        for (Course course : courses) {
            modelCourses.addRow(new Object[]{
                course.getId(),
                course.getTitle(),
                course.getDescription(),
                course.getPriceText(),
                course.getInstructorName()
            });
        }
    }
    
    private void loadMyEnrollments() {
        modelEnrollments.setRowCount(0);
        int studentId = Session.getCurrentUser().getId();
        List<Enrollment> enrollments = enrollmentDAO.findByStudent(studentId);
        
        for (Enrollment enrollment : enrollments) {
            modelEnrollments.addRow(new Object[]{
                enrollment.getId(),
                enrollment.getCourseTitle(),
                enrollment.getEnrolledDate()
            });
        }
    }
    
    private void enrollCourse() {
        int row = tableCourses.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn khóa học!");
            return;
        }
        
        int courseId = (int) modelCourses.getValueAt(row, 0);
        int studentId = Session.getCurrentUser().getId();
        
        // Check if already enrolled
        if (enrollmentDAO.isEnrolled(studentId, courseId)) {
            JOptionPane.showMessageDialog(this, "Bạn đã đăng ký khóa học này rồi!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Xác nhận đăng ký khóa học này?", 
            "Xác nhận", 
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            Enrollment enrollment = new Enrollment(studentId, courseId);
            
            if (enrollmentDAO.insert(enrollment)) {
                JOptionPane.showMessageDialog(this, 
                    "Đăng ký thành công!\nBạn có thể bắt đầu học ngay.", 
                    "Thành công", 
                    JOptionPane.INFORMATION_MESSAGE);
                loadMyEnrollments();
            } else {
                JOptionPane.showMessageDialog(this, "Đăng ký thất bại!");
            }
        }
    }
    
    private void logout() {
        Session.logout();
        new LoginFrame().setVisible(true);
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
